version: '3'
services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADOR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8085:8080"
    depends_on:
      - mysql
    
#volumes:
  #mysqL_data:
    #driver: local
  #services:
  #keycloak: 
    #image: quay.io/keycloak:12.0.4
    #environment:
       #DB_VENDOR: MYSQL
        #DB_ADOR: mysql
        #DB_DATABASE: keycloak
        #DB_USER: keycloack 
        #DB_PASSWORD: DB_PASSWORD  
        #KEYCLOAK_USER: admin
        #KEYCLOAK_PASSWORD: admin
    #ports:
      #- "8085:8080"
    #depends_on:
      #- mysql
  #mysql:
    #image: mysql:5.7
    #ports:
      #- "3306:3306"
    #volumes:
      #- mysql_data:/var/lib/mysql
    #environment:
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: keycloak
      #MYSQL_USER: keycloak
      #MYSQL_PASSWORD: password
